### ISSUE TITLE
Improve detected device names

### ISSUE THREAD

**Issue by sgiehl** [piwik/device-detector#5247]
Most producers have internal and marketing names for their devices. Samsung for example uses complete different internal names for some devices. The _Galaxy S4_ identifies itself with _SC-04E_ and _Galaxy Note 3_ uses _SC-01F_. As those internal names aren’t really useful, the best solution would be to replace them with their marketing names. That is already done for some devices, but for most devices the internal name will be returned.
We are planning to change this behavior by creating proper mappings from internal to marketing names. As it is very time consuming to do lookups for those mappings we need your help, to support us getting this done.

**Comment by pksh** [comment]
Would it be wise to make use of resources like WURFL http://wurfl.sourceforge.net/ which do give these details and its DB is maintained quite frequently?

**Comment by jcalderonzumba** [comment]
@pksh WURLF has changed their license and if you use their data you basically force anyone using your library to opensource their entire code base as per their new license.

**Comment by ThaDafinser** [comment]
Some of the names could be taken from this list
http://thadafinser.github.io/UserAgentParserComparison/v5/detected/PiwikDeviceDetector/device-models.html

then click on the detail, you will find sometimes better name from other parsers, e.g.
http://thadafinser.github.io/UserAgentParserComparison/v5/user-agent-detail/3e/e3/3ee345ec-434a-4e5d-951e-373068c3abba.html

**Comment by sgiehl** [comment]
As that's an ongoing tasks I'll close the issue. I'm always trying to improve the names where possible...
