### ISSUE TITLE
Possible to get model number ?

### ISSUE THREAD

**Issue by nodeffect** [piwik/device-detector#5298]
It's not really a bug but....

Is it possible to get the model number also ? For example, for this user agent, "Mozilla/5.0 (Linux; Android 4.4.4; D5503 Build/14.4.A.0.157) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.59 Mobile Safari/537.36"

I'm able to get the brand and model which is "Sony" and "Z1 compact". But, I'm not able to get the model number which is "D5503".

**Comment by sgiehl** [comment]
For some useragent it maybe would be possible to implement that. But as many uas just contain a clear name instead of the model number I would have to provide a mapping for all devices. And that is just too much work.

**Comment by nodeffect** [comment]
It's cool, totally understand that.... Thank you so much for your fast response. ;)
