### ISSUE TITLE
Apple iPhone/iPad device UA are detected as Unknowns

### ISSUE THREAD

**Issue by pksh** [piwik/device-detector#5301]
Recently I followed you documentation and ran this command "https://github.com/piwik/device-detector#listing-all-user-agents-from-your-logs" on my access log and found that majority of them were of these formats.
Details from partial report below:
971 Apple-iPhone5C2/1104.201
448 Apple-iPhone4C1/1202.440
305 Apple-iPhone7C1/1202.440
290 Apple-iPhone6C2/1202.440
275 Apple-iPhone5C4/1202.440
39 Apple-iPhone3C1/1104.257
36 Apple-iPhone6C2/1104.201
36 Apple-iPad3C3/1202.440
26 Apple-iPhone6C2/1104.257
25 Apple-iPhone7C2/1202.440
25 Apple-iPhone4C1/1104.257
23 Apple-iPhone5C2/1202.440
19 Apple-iPhone5C2/1102.55400001
14 Apple-iPhone5C2/1104.257
12 Apple-iPad2C7/1002.329
   9 Apple-iPhone6C2/1202.411
   9 Apple-iPhone5C4/1104.201
   9 Apple-iPhone4C1/1104.201
   9 Apple-iPhone4C1/1102.55400001
   8 Apple-iPhone5C2/1202.435
   8 Apple-iPhone3C2/1104.201
   6 Apple-iPod5C1/1202.440
   6 Apple-iPhone6C2/1104.167
   6 Apple-iPhone5C2/1202.411
   6 Apple-iPhone4C1/1102.511
   6 Apple-iPhone2C1/1002.500
   6 Apple-iPad2C5/1202.440
   5 Apple-iPhone5C4/1104.257
   5 Apple-iPhone5C2/1102.651
   5 Apple-iPad4C4/1202.440
   5 Apple-iPad2C1/1202.440
   4 Apple-iPod5C1/1104.257
   4 Apple-iPod5C1/1104.201
   4 Apple-iPod4C1/1002.500
   4 Apple-iPhone3C1/1104.169
   4 Apple-iPad4C1/1202.440
   4 Apple-iPad3C4/1202.440
   4 Apple-iPad3C4/1202.410
   2 Apple-iPod5C1/1201.405
   2 Apple-iPhone6C2/1201.405
   2 Apple-iPhone4C1/1104.167
   2 Apple-iPad4C2/1202.440
   2 Apple-iPad2C7/1104.257
   2 Apple-iPad2C2/1104.201
   1 Apple-iPhone7C2/1202.411
   1 Apple-iPhone7C1/1201.366
   1 Apple-iPhone6C1/1202.440
   1 Apple-iPhone6C1/1104.201
   1 Apple-iPhone5C4/1102.55400001
   1 Apple-iPhone5C4/1102.511
   1 Apple-iPhone5C4/1101.466
   1 Apple-iPhone5C3/1104.257
   1 Apple-iPhone5C2/1201.365
   1 Apple-iPhone5C2/1104.167
   1 Apple-iPhone5C1/1202.440
   1 Apple-iPhone4C1/1202.411
   1 Apple-iPhone3C2/1104.169
   1 Apple-iPhone3C1/901.334
   1 Apple-iPad4C7/1201.365
   1 Apple-iPad4C4/1201.365
   1 Apple-iPad3C6/1104.257
   1 Apple-iPad3C4/1104.257
   1 Apple-iPad3C3/1202.435
   1 Apple-iPad3C1/1201.405
   1 Apple-iPad2C5/1202.435

We tried some of them using Device Detector from Piwik Admin Page resulting into Unknowns for all the fields.

An extensive list of UA could be found at "http://www.enterpriseios.com/wiki/Complete_List_of_iOS_User_Agent_Strings"

Note: We are using PHP Tracker API and piwik/device-detector (2.8.1)

**Comment by sgiehl** [comment]
Thx. I'll have a look at that the next days

**Comment by pksh** [comment]
Brilliant Thanks. That was quick response. 

And are you guys looking at when trying to detect a laptop/desktop UA, the device brand ends up as Unknown but instead having it classified into Generic Laptop/Desktop would dramatically reduce the chance. Any thoughts??

**Comment by pksh** [comment]
Brilliant

**Comment by andriibaliozstrikead** [comment]
Hi, but can you please advice if we can recognize iPhone 5c and iPhone 6 if UA string do not contain next type of properties: "Apple-iPhone5C2/" ?

**Comment by sgiehl** [comment]
If the useragent does not contain any device fragment this library is not able to detect it.

**Comment by andriibaliozstrikead** [comment]
Can you please advice in example what the device model fragments must be presented for iPhones and iPads. Thank you

**Comment by sgiehl** [comment]
iPhone or iPad is enough to be detected. It may also be Apple-iPhoneXXX for specific iPhones
And it's not relevant at which position in the useragent it occurs.
If you have any useragent that are not detected correctly. Please open a ticket and post it, so I can check if I can improve the detections for that.

**Comment by olivierphl** [comment]
I have a question on something that is very important to me .  It is going to sound like a stupid detail :(

An IPhone 5 was synch to an office 365 email. It did capture the correct devide ID number and IOS and type of Iphone ( an iPhone5) BUT instead of giving the correct iOS User-Agent String it gave an incorrect one. I believe the iOS User-Agent String listed for this iPhone 5 is Apple:

Apple-iPhone5C1/1001.525

but the one captured by Office 365 is showing

Apple-iPhone5C1/1101.5

Why would that be?  Isn't this automated? Why would a program like Office 365 not get the correct name and number??

Thanks .  Hopefully one of you geniuses can shed some light on this for me :)
