### ISSUE TITLE
Extremely low performance

### ISSUE THREAD

**Issue by MaxBaldin** [piwik/device-detector#5307]
Hello! Here is the code(as in example):
```php
<?php
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\DeviceParserAbstract;

require_once("../device-detector/vendor/autoload.php");

DeviceParserAbstract::setVersionTruncation(DeviceParserAbstract::VERSION_TRUNCATION_NONE);

$dd = new DeviceDetector();

$dd->setUserAgent("Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0");
$dd->parse();

$clientInfo = $dd->getClient();
print_r($clientInfo);
```

It takes about **10 seconds** to parse one user-agent.

php -v result:
```shell
PHP 5.5.20 (cli) (built: Dec 17 2014 12:09:22)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```
php extensions: redis, memcache, xdebug
operation system: windows 8.1 x64.

Xdebug profiler snapshot: https://www.dropbox.com/s/mecp952mj5wocia/cachegrind.out.7z?dl=0

99,6% takes method DeviceDetector\DeviceDetector->parse with extremelly long preg_match calls(6.321 sec). 

I`m a bit confused, is it ok? Is this library only for raw data post-processing and not for real-time user-agent parsing?

**Comment by sgiehl** [comment]
For sure the preg_match calls will take the most of the time.
Havn't tested it on Windows yet, but on my virtual Linux box it takes less than a second to parse and using a cache after the first parse it takes around 0,05s to parse the following ones.

I guess xdebug slows down your results a lot. Have you tried it without?

**Comment by ThaDafinser** [comment]
I use it on windows (production) and dont have problems with it....when cache enabled

**Comment by ve3** [comment]
I'm using it on Windows 10 PHP 7.0 it take about 1.x second without cache. Too slow.

**Comment by Findus23** [comment]
@ve3 As mentioned in https://github.com/matomo-org/device-detector/issues/5964#issuecomment-494125734 it takes about 50ms (including HTTP and SSL overhead) on https://devicedetector.lw1.at/ using the redis cache, but every other (memory based) cache should also get you a similar performance.
