### ISSUE TITLE
Which dimension is identify Mobile/PC/Tablet info?

### ISSUE THREAD

**Issue by abbo** [piwik/device-detector#5309]
Hi guys,
Q1
Which dimension is identify Mobile/PC/Tablet info?
Q2
I see the oss.yml contain Mac/iOS ,but in my opnion, that is should OS X and iOS(system name).What's wrong for that?
Thank you

**Comment by sgiehl** [comment]
Q1:
After parsing you can call getDevice() / getDeviceName() to get information what device type has been detected. It might contain more than only mobile/tablet/pc.
There's also an isMobile() method which returns if the device was detected as any mobile device or an device running an mobile only os.

Q2:
Not all Mac are running OS X. Before the system was called Mac OS
