### ISSUE TITLE
Add detection of "phablets"

### ISSUE THREAD

**Issue by torbenbrodt** [piwik/device-detector#5318]
Hey,
i would find it very interesting to react on the growing share of Phablets.
I think Phablet is nowaday an accepted term when talking about device types.

Phablets can do phone calls, but have a large screen (according wikipedia Phablets measure (diagonally) between 5.3 to 6.9 inches)

This information is a not as abstract as "phone and tablet", its not as precise as "the full featured device list" but its giving a bit more information to webmasters who want to tweak their website.

How do you think about it?

**Comment by sgiehl** [comment]
Would be interesting. But it would be much work to look up all phablet devices and add a proper detection.

**Comment by torbenbrodt** [comment]
Definetly some work. Phablet is mostly defined by the screen dimensions and thats what we don't have via the http headers. The information would be sourced from manufacturer websites or other external sources like http://www.laptopmag.com/best-phablets

I am interested in helping. I would also try to update the phablets i can gather from such sources and send a pull request. But of course i don't want to introduce a new "device type" before discussing it here.

**Comment by sgiehl** [comment]
I've spent some thoughts on it. Let's add the new device type.
I'll prepare everything to have the new device type. Afterwards you can go ahead and improve/change/add the regexes for phablets

**Comment by torbenbrodt** [comment]
Thx

pushed more devices via #5323
