### ISSUE TITLE
Fix detection for Samsung Galaxy Tab

### ISSUE THREAD

**Issue by edibusl** [piwik/device-detector#5319]
When choosing Galaxy Tab tablet in Chrome's Debugging Tools console, it uses the following user agent:
Mozilla/5.0 (Linux; U; Android 2.2; en-us; SCH-I800 Build/FROYO) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

And it is parsed as SMARTPHONE instead of TABLET.

**Comment by sgiehl** [comment]
Guess the detections are not accurate for Galaxy Tab. SCH-I800 is not detected as Galaxy Tab. I'll add that
