### ISSUE TITLE
DeviceDetector\Parser\Client\Browser class lacks browser family mapping for some browsers

### ISSUE THREAD

**Issue by edibusl** [piwik/device-detector#5320]
In class DeviceDetector\Parser\Client\Browser
$availableBrowsers array includes the following browsers: Baidu, Amiga, Palm
Which have more than one type, but don't have a suitable browser family in the $browserFamilies array.
I'm not sure whether it's a bug or it's in purpose.

**Comment by sgiehl** [comment]
That feature is more or less legacy code. Imho that mapping does not make sense at all. Maybe I will remove that in the next major release

**Comment by edibusl** [comment]
Why it doesn't make sense? For example, I would like to treat "Chrome"/"Chrome Mobile"/"Chromium" as "Chrome"

**Comment by sgiehl** [comment]
Maybe it makes sense in some special cases. I can leave that detection in the code for sure. But the list is already quite outdated and I guess there are more detected browsers based on chromium. Btw. I guess it would be more correct to name the family chromium, as chrome is also based on chromium.
I currently don't have time to look up all browsers if they are based on another one. If you like feel free to do that and create a pull request. Otherwise it may take some time

**Comment by edibusl** [comment]
I don't think that it's important that Iron and Chrome are of the same family.
What I actually meant it to group similar browsers, for example "Chrome"/"Chrome Mobile"/"Chrome Mobile iOS" should be grouped to Chrome.
"Baidu Browser"/"Baidu Spark" should be grouped to "Baidu"
That should be much simpler. I can make that change, but as I look on the browsers list, I'm not sure that it's updated.
Take a look on the browser list of Udger (https://udger.com/resources/ua-list)
It seems that there are lots of browsers missing from the list.

**Comment by sgiehl** [comment]
I'm only adding new browsers when I see example useragents anywhere. So it might be possible that rarely used browsers are not in the list right now. 
I still have a long list of useragents from log files to check, maybe there will be some undetected browsers in it. But currently my focus is more on adding detection for new devices.
If I have some time, I'll go through the list at udger and add some more missing ones.

**Comment by edibusl** [comment]
Great.
I can group Baidu, Amiga and Palm user agents to families in the $browserFamilies array.
It's only 2 lines of code, so I hope that I really help here. Would you like me to do it?

**Comment by sgiehl** [comment]
Sure. Feel free to create a pull request for that. But please also adjust the tests affected by that change.

**Comment by edibusl** [comment]
Stefan, I made the changes and also adjusted the tests. Should I create a new branch and then make a pull request? Because I don't have permissions to push to the master branch.

**Comment by sgiehl** [comment]
You need to fork the repo in order to push something and create a pull request.

**Comment by edibusl** [comment]
Got it. Please check the pull request.
