### ISSUE TITLE
Piwik reports Linux as Mac

### ISSUE THREAD

**Issue by LPTM4** [piwik/device-detector#5326]
Posted on the forum (http://forum.piwik.org/read.php?2,125405), reposted here as per request:

I just installed Piwik for my website and test visited it.
I'm running Linux Mint 18.1 on my laptop but Piwik recognizes it as 'Mac'. I was unable to find any more detailed specification, just 'Mac'. All the other parameters (browser, screensize etc.) are perfectly fine.

**Comment by sgiehl** [comment]
Could you please post the useragent. You can look yours up at http://whatsmyuseragent.com/

**Comment by LPTM4** [comment]
Hm, interesting.

Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-us) AppleWebKit/537+ (KHTML, like Gecko) Version/5.0 Safari/537.6+ Midori/0.4

So maybe more a browser issue than a piwik issue?

**Comment by sgiehl** [comment]
Seems to be. You are using Midori browser?
