### ISSUE TITLE
Piwik doesn't make the difference between Internet Explorer and project spartan

### ISSUE THREAD

**Issue by baywet** [piwik/device-detector#5329]
Microsoft publicly released a new browser yesterday.
 After trying it out it seems that Piwik doesn't make the difference between Spartan and IE users.
 It'd be great to have this information.
IE11 on w10 (10049): Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0
 Spartan (same system): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0
Note: previously opened here https://github.com/piwik/piwik/issues/7603#issuecomment-88366506 but moved over

**Comment by sgiehl** [comment]
I had added that detection before the new name has been announced. I'll adjust that

**Comment by sgiehl** [comment]
Are you sure the first mentioned useragent is correct? It's the same as the second...

**Comment by baywet** [comment]
Well this is not exactly the same IE has WOW64 and Spartan has Win64; x64. I went to http://whatsmyuseragent.com/ to get these results. Any idea on how to get anything more precise? I can ping the PM for Spartan also if you'd like to.

**Comment by sgiehl** [comment]
IE11 on Windows 10 shouldn't mask himself as Chrome. That is only done by "Porject Spartan".
IE11 should be something like ```Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko```

**Comment by baywet** [comment]
That's something they added to windows phone a while ago because people kept on serving "ie6 pages" when they detected IE causing issues. I guess they brought that to windows 10 too as a result of the merge of the two OS's When I change it to the IE11 with developer tools it gives me that Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko

**Comment by sgiehl** [comment]
I'm gonna add detection of "Project Spartan" for Edge/XX.XX, as that seems to be the only way right now. Maybe Mircosoft adds their own useragent fragment for "Project Spartan" when it's final. Otherwise the detection will never be very accurate. But that seems to be the creepy way Mircosoft wants to go to avoid the shit they caused with Internet Explorer :hankey:

**Comment by baywet** [comment]
Right, there's a long story behind that. Do you want me to try to ping one of the PM's of Spartan on the user agent thing to know if they are going to change it?

**Comment by sgiehl** [comment]
sure. Feel free to ask.

**Comment by deltakosh** [comment]
I confirm: To detect Sparta you have to find Edge/XX.
Just a reminder of "creepy way" that ALL browser used to use:
http://webaim.org/blog/user-agent-string-history/

**Comment by sgiehl** [comment]
@deltakosh Thx for the confirmation! Is the version given in ```Edge/XX``` the version of "Project Spartan" - so will that change for future versions or will there be another indicator for that?

**Comment by deltakosh** [comment]
Correct, the number will be increased with future versions

**Comment by sgiehl** [comment]
Ok. Thanks. So my implementation is correct.
