### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/device-detector#5333]
Hello,

i have some ideas to further improve the device detector

1) Remove/deprecate the static function: https://github.com/piwik/device-detector/blob/master/DeviceDetector.php#L644-L647
Some folks will use it (already saw that) and report the component is slow, although its fast with the cache

2) use the php-cs-fixer to fix psr2 issues on the fly https://github.com/piwik/device-detector/blob/master/DeviceDetector.php#L644

**Comment by sgiehl** [comment]
Adding a comment to that method makes sense...

**Comment by sgiehl** [comment]
as the comment was added, and your PR for php-cs-fixer has been merged. I'll close that ticket...
