### ISSUE TITLE
add demo

### ISSUE THREAD

**Issue by 9px** [piwik/device-detector#5348]
hi. is it possible to add a demo page?
i download and configure Piwik device detector locally but in some browser i get an error. i like to see an online demo version of this repository so i can find that the problem is from my installation or from this repository.

**Comment by sgiehl** [comment]
I'm building a demo page. It will be available on http://devicedetector.net as soon as I'm finished. Stay tuned!

**Comment by 9px** [comment]
thanks. i'm waiting...

**Comment by sgiehl** [comment]
A very basic demo is online now. but there aren't much features yet. I'll add some more stuff there, as soon as I got some more time for it
