### ISSUE TITLE
Detected browser engine was not found in $availableEngines

### ISSUE THREAD

**Issue by smilesrg** [piwik/device-detector#5354]
Honesty, I don't think that this exception must be ever thrown. Why just don't return empty string instead?

I faced with that exception when tried to detect device from bot user-agent string.

**Comment by sgiehl** [comment]
Would you mind posting a sample code / useragent that causes that exception?

**Comment by sgiehl** [comment]
That should be fixed with 984725994f75ddb663caa0bbfef0798862afd23b
