### ISSUE TITLE
Piwik don't see Opera 64 and Waterfox 64

### ISSUE THREAD

**Issue by MESWEB** [piwik/device-detector#5357]
Piwik see only Google Chrome from this three browsers. Why?

**Comment by sgiehl** [comment]
Hi. Could you provide some example useragents that I can use to add detection for waterfox 64 and opera 64?

**Comment by MESWEB** [comment]
i did it. I resolve this issue. Just disable ublock on Waterfox and adblock on Opera. So why piwik image not working when someone using any ad blocker?

**Comment by sgiehl** [comment]
That depends on the adblocker you use. Some adblockers have piwik.js or similar in the blocklist. Unfortunately there is absolutely nothing we can do to change that.
