### ISSUE TITLE
Use adapters for the YAML parser

### ISSUE THREAD

**Issue by shulard** [piwik/device-detector#5365]
Hello !

I found your lib which seem really useful and I want to integrate it in my project. I already use YAML files for my configuration, but I use the symfony/yaml parser.

I saw that you use another one: mustangostang/spyc

I think it can be useful to be able to choose which YAML loader must be used inside the lib. Because it's a lib, the user can choose which one he want to use the same way that cache adapter.

If you think it can be useful, I can work on a PR...

**Comment by sgiehl** [comment]
I evaluated to use symfony/yaml before. But it was a lot slower in parsing. Therefor I decided to use a slimmer, faster one.

**Comment by shulard** [comment]
Of course, I understand that but I think it's not really nice for me to deal with different parser in my project. 
There is also a PHP extension to deal with Yaml... Don't you think that it can be interesting to being able to swap the loader ?

**Comment by sgiehl** [comment]
Well, I think it should still be required by composer and be the default lib for YAML, but maybe we could build a facade pattern to allow switching the underlaying YAML lib.
