### ISSUE TITLE
How to detect HbbTv Version

### ISSUE THREAD

**Issue by moslani** [piwik/device-detector#5370]
Hi All,

The is a need to detect HbbTV version from the useragent. Can anyone let me know which files should be modified to get it done. Here is an example for an useragent with HbbTv Version in it. 

Opera/9.80 (Linux mips ; U; **HbbTV/1.1.1** (; Philips; ; ; ; ) CE-HTML/1.0 NETTV/3.2.1; en) Presto/2.6.33 Version/10.70

**Comment by sgiehl** [comment]
I've done some small adjustments to make that easily possible.
Using the HbbTv Parser you can now get the version.
See the test for a code example: https://github.com/piwik/device-detector/blob/master/Tests/Parser/Devices/HbbTvTest.php
