### ISSUE TITLE
Regarding device detector report problem

### ISSUE THREAD

**Issue by redbox2000** [piwik/device-detector#5379]
Hi 
I am facing device detector problem .

Example UA
Dalvik/1.6.0 (Linux; U; Android 4.1.2; SO-03D Build/9.2.C.1.102

If I searched from DevicesDetection page under the admin control panel,it detected OS and device type and more.
But Piwik device reports was unknown status.

Could you please advice me? My piwik version is 2.13.1

Best regards.

**Comment by sgiehl** [comment]
You my need to update Piwik. DeviceDetector is bundled with Piwik and the definitions are currently only update with a Piwik update.

Btw.: Piwik itself currently is not able to handle everything DeviceDetector is able to detect.
Piwik ignores all clients other the browser and shows them as unknown
