### ISSUE TITLE
android not detected as phone but as mobile 

### ISSUE THREAD

**Issue by dfrieling** [piwik/device-detector#5382]
the following user agents are detected as _mobile_ but piwik does not report if it's _phone_,_tablet_ or _phablet_.

* [x] Mozilla/5.0 (Linux; Android 5.0.2; PLK-L01 Build/HONORPLK-L01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36 
* [x] Mozilla/5.0 (Linux; Android 4.4; CT1000 Build/KRT16S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36
* [x] Mozilla/5.0 (Android 5.1.1; Mobile; rv:42.0) Gecko/42.0 Firefox/42.0
* [ ] Mozilla/5.0 (Linux; Android 4.4.2; MR100Z1H1CW1 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36 MxBrowser/4.5.4.1000
* [x] Mozilla/5.0 (Linux; Android 4.4.2; BUSH 5 Android Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/54.0.0.23.62;] 
* [x] Mozilla/5.0 (Linux; Android 5.0.2; E6553 Build/28.0.A.8.251) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36 
* [x] Mozilla/5.0 (Linux; Android 5.0; E2303 Build/26.1.A.2.167; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/54.0.0.23.62;] 
* [x] Mozilla/5.0 (Android 4.4.2; Mobile; rv:42.0) Gecko/42.0 Firefox/42.0 
* [ ] Opera/9.80 (Android; Opera Mini/7.6.40234/37.7059; U; pl) Presto/2.12.423 Version/12.16 
* [ ] MT6582_TD/V3 Linux/3.4.67 Android/4.4.2 Release/ Browser/AppleWebKit537.36 Chrome/30.0.0.0 Mobile Safari/537.36 System/Android 4.4.2; 

I assume these should be detected as _phone_. Chrome's help page might be useful here: https://developer.chrome.com/multidevice/user-agent. They say the patterns are:
* Phone pattern: 'Android' + 'Chrome/[.0-9]* Mobile'
* Tablet pattern: 'Android' + 'Chrome/[.0-9]* (?!Mobile)'

What do you think, is this just missing rules or a won't fix?

**Comment by sgiehl** [comment]
I'll have a look at the useragents. I guess the devices are not detected for those.

But the device type detection based on the chrome user agent might be worth to have an additional look...

**Comment by sgiehl** [comment]
All checked UAs should now be detected correctly.

For the unchecked:

`Opera/9.80 (Android; Opera Mini/7.6.40234/37.7059; U; pl) Presto/2.12.423 Version/12.16`
--> it is not possible to detect the device type using this useragent as it does not contain any fragment, that would point to phone, tablet or phablet.

`MT6582_TD/V3 Linux/3.4.67 Android/4.4.2 Release/ Browser/AppleWebKit537.36 Chrome/30.0.0.0 Mobile Safari/537.36 System/Android 4.4.2;`
--> is now detected as phone, based on the Chrome Mobile fragment. A brand or model can't be detected here as `MT6582` only points to the used MediaTek chipset.

`Mozilla/5.0 (Linux; Android 4.4.2; MR100Z1H1CW1 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36 MxBrowser/4.5.4.1000`
--> didn't find a exact definition what `MR100Z1H1CW1` stands for. But I've put that on my list to check that later again.
