### ISSUE TITLE
Please check all User-Agents from this list

### ISSUE THREAD

**Issue by FDiskas** [piwik/device-detector#5383]
https://udger.com/resources/ua-list/device-detail?device=Smart%20TV

**Comment by FDiskas** [comment]
For example
```Mozilla/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1```
this does not shows device as TV
But this one is ok:
```
Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebkit/537.42 (KHTML, like Gecko) Safari/537.42
```

**Comment by mattab** [comment]
Hi @FDiskas  thanks for the suggestion. Maybe you could help us improve the detection by submitting a pull request? https://github.com/piwik/device-detector#contributing

**Comment by sgiehl** [comment]
The mentioned one should be detected correct now. I'll see if I have some time to check the other ones on the mentioned list
