### ISSUE TITLE
Installing without composer

### ISSUE THREAD

**Issue by omerfarukgerdan** [piwik/device-detector#5388]
Hello,

Can you supply a documentation to install device detector without composer? There is only this thread http://stackoverflow.com/questions/30011230/how-to-use-piwik-device-detector-in-php-project giving information but not satisfactory.

Composer installation includes tests and other unused directories/files, which most people may not prefer.

It should be as smooth as only require/include one file, DeviceDetector.php.

**Comment by ThaDafinser** [comment]
-1 from me.

Let the developers focus on getting things done and not introduce "old behaviour" there are enough tutorials around how to write a custom autoloader

**Comment by sgiehl** [comment]
We won't change that behavior. Instead of using composer you may use any other autoloader.
