### ISSUE TITLE
Duplication of test `bots.yml`

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/device-detector#5420]
Hello,

`bots.yml` is in two places
https://github.com/piwik/device-detector/tree/master/Tests/fixtures
https://github.com/piwik/device-detector/tree/master/Tests/Parser/fixtures

The file in Parser is filled with more result data. Is therer any reason for it, to keep it seperate?

//cc @sgiehl

**Comment by sgiehl** [comment]
One is used for testing the BotParser class directly. The other one is used for testing DeviceDetector class to parse the useragent. I'll have a look at that. Guess we could remove one...

**Comment by ThaDafinser** [comment]
Thank you.

Will update my test suite

**Comment by ThaDafinser** [comment]
@sgiehl i just noticed, that the bot category is lost now in the test fixtures

https://github.com/piwik/device-detector/blob/470689dafab02b79806d4f85feb29e16a4077cfb/Tests/Parser/fixtures/bots.yml#L164-L167

https://github.com/piwik/device-detector/blob/master/Tests/fixtures/bots.yml

**Comment by sgiehl** [comment]
Even if that's not really necessary for our tests, I'll reinclude all data again...
