### ISSUE TITLE
Facebook User Agent

### ISSUE THREAD

**Issue by Ninestein** [piwik/device-detector#5425]
Hi,

was trying to detect Facebook Native Application browser and it doesn't seem to pick it up, or at least the test strings I can find.

Two examples being:
> Mozilla/5.0 (iPad; U; CPU iPhone OS 5_1_1 like Mac OS X; en_US) AppleWebKit (KHTML, like Gecko) Mobile [FBAN/FBForIPhone;FBAV/4.1.1;FBBV/4110.0;FBDV/iPad2,1;FBMD/iPad;FBSN/iPhone OS;FBSV/5.1.1;FBSS/1; FBCR/;FBID/tablet;FBLC/en_US;FBSF/1.0]

> Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/35.0.0.48.273;]

Some good examples here:
https://mobiforge.com/research-analysis/webviews-and-user-agent-strings

Seems to be based around the FBAN, FBAV values across devices.

Is there a reason you're detecting WeChat but not Facebook? Or is that string unreliable? Or am I calling the wrong method?

Thanks

**Comment by sgiehl** [comment]
There is a detection for facebook, but it only matches for other fragments.
I'll have a look at your suggestion soon and extend the detection if it
makes sense.

**Comment by Ninestein** [comment]
Thanks for adding that in. Saw you did WhatsApp and Pinterest too. Awesome!
