### ISSUE TITLE
Add detection for iNew smartphone

### ISSUE THREAD

**Issue by huigjr** [piwik/device-detector#5439]
Mozilla/5.0 (Linux; Android 4.4.2; V7A Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

Browser: Android Browser
OS: Android 4.4.2
Device: Smartphone
Brand: iNew
Model: V7A

Device is currently detected as generic android device running Chrome. This is not correct

**Comment by sgiehl** [comment]
Thanks for the useragent/device specs. I'll add the detection soon
