### ISSUE TITLE
SkypeUriPreview bot not being detected

### ISSUE THREAD

**Issue by DarkN3ss61** [piwik/device-detector#5459]
SkypeUriPreview isnt being detected as a bot:

Mozilla/5.0 (Windows NT 6.1; WOW64) SkypeUriPreview Preview/0.5

**Comment by DarkN3ss61** [comment]
With the latest update installed, it still doesn't seem to be getting detected as a bot, even on your demo site it doesn't

**Comment by sgiehl** [comment]
A new version wasn't released yet. You may need to use master in order to have this detection. Live demo will be updated with next release, aswell
