### ISSUE TITLE
New inapp user agents CFNetwork

### ISSUE THREAD

**Issue by dfrieling** [piwik/device-detector#5461]
there are user new agents around that are detected as deviceType=desktop even though we saw them in an in-app context:
CFNetwork/758.2.8 Darwin/15.0.0
CFNetwork/758.3.15 Darwin/15.4.0

The first (CFNetwork/758.2.8 Darwin/15.0.0) is identified as iOS 9.2 on https://user-agents.me/cfnetwork-version-list, the second seems to be too new to be known. Maybe anybody knows?

For the first I would add:
```
- regex: 'CFNetwork/758\.2\.[78]'
  name: 'iOS'
  version: '9.2'
```
to regexes/oss.yml but I cannot push my feature branch.

**Comment by va5ja** [comment]
CFNetwork/758.3.15 Darwin/15.4.0 seems to be upcoming iOS 9.3
https://www.theiphonewiki.com/wiki/Kernel
