### ISSUE TITLE
i cant parse "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

### ISSUE THREAD

**Issue by nambak** [piwik/device-detector#5465]
i cant parse "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko".
use device detector library, getClient() method anything return.
but,  in demo page(http://devicedetector.net/) can parse it.
what I did wrong?

**Comment by ThaDafinser** [comment]
@nambak 2 ideas:
- upgrade to the latest version https://github.com/piwik/device-detector/releases
- check if you messed up encoding / special characters

**Comment by nambak** [comment]
- i cheked device detector version 3.6.
- my database / php encording is utf-8/unicode.

single string parse is fine. but many string in array, Still not parsed.

**Comment by sgiehl** [comment]
DeviceDetector is currently not able to parse multiple useragents at once. You need to do that in a loop.

Example code (untested)
```php
$userAgents = ['ua1', 'ua2']; // array with useragents
$results = []; // array with results
$deviceDetector = new DeviceDetector();

foreach ($userAgents as $userAgent) {
    $deviceDetector->setUserAgent($userAgent);
    $deviceDetector->parse();
    // do anything with parsed result
   echo $deviceDetector->getClient('name');
}
```

**Comment by nambak** [comment]
@sgiehl , @ThaDafinser thank you for support 
@sgiehl, your code is working good.

and i was coded like this :
`$userAgent = [ ] // array with many user agent string...

foreach ($userAgents as $userAgent) {
  $deviceDetector = new DeviceDetector($userAgent);
  $deviceDetector->parse();
  // display parsed result...`
