### ISSUE TITLE
Opera Mini user agent

### ISSUE THREAD

**Issue by va5ja** [piwik/device-detector#5466]
Currently Piwik doesn't detect device type for the following user agents:

**Opera (mobile)**
- Opera/9.50 (J2ME/MIDP; Opera Mini; U; en)
- Opera/9.50 (J2ME/MIDP; Opera Mini/2/29.3757; U; en)
- Opera/9.50 (J2ME/MIDP; Opera Mini/4.2.1214/29.3757; U; en)
- Opera/9.50 (J2ME/MIDP; Opera Mini/4.2.1258/29.3757; U; ro)
- Opera/9.50 (J2ME/MIDP; Opera Mini/5.1.2152/29.3757; U; en)
- Opera/9.50 (J2ME/MIDP; Opera Mini/6.1.27786/29.3757; U; hu)
- Opera/9.50 (J2ME/MIDP; Opera Mini/7.0.32351/29.3757; U; de)
- Opera/9.50 (J2ME/MIDP; Opera Mini/7.5.32382/29.3757; U; en)
- Opera/9.50 (J2ME/MIDP; Opera Mini/7.6.40234/29.3757; U; de)
- Opera/9.80 (J2ME/MIDP; Opera Mini; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/4.0.10031/37.8069; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.13068/37.8069; U; it) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/4.2.13057/37.8069; U; ru) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/8.0.40377/37.8069; U; uk) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/9.5/37.8069; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (J2ME/23.377; U; en) Presto/2.5.25 Version/10.54
- Opera/9.80 (MAUI Runtime; Opera Mini/4.4.31259/37.8069; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (MAUI Runtime; Opera Mini/6.1.27412/37.8069; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (SpreadTrum; Opera Mini/4.4.31492/37.8090; U; en) Presto/2.12.423 Version/12.16
- Opera/9.80 (SpreadTrum; Opera Mini/4.4.34080/37.8069; U; th) Presto/2.12.423 Version/12.16
- Opera/9.80 (VRE; Opera Mini/4.2/37.8069; U; en) Presto/2.12.423 Version/12.16
- and similar (different languages and versions)...

It would be great to add support.

**Comment by sgiehl** [comment]
There is no device fragment in the useragents, so there is no proper way to
detect it.

**Comment by va5ja** [comment]
Well it's clearly Opera Mini, so a browser used on mobile devices. Probably phone, could be tablet or phablet but at least the mobile flag should be enabled.

**Comment by sgiehl** [comment]
OK. I'll check that isMobile() will return true for Opera Mini
