### ISSUE TITLE
Tablet is detected as mobile

### ISSUE THREAD

**Issue by frankvanrest** [piwik/device-detector#5469]
Mozilla/5.0 (Linux; Android 5.0.2; K01B Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.91 Safari/537.36

This is a tablet device:
https://www.asus.com/Tablets/ASUS_Transformer_Pad_TF303K/

But it is detected as a mobile device.

**Comment by sgiehl** [comment]
Thanks, I'll add the detection.
