### ISSUE TITLE
WebTV = Model and not brand?

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/device-detector#5478]
Dunno which one is right, but more clain that WebTV is the model and not the brand.

http://useragent.mkf.solutions/?userAgent=Mozilla%2F4.0+WebTV%2F2.8+%28compatible%3B+MSIE+4.0%29

**Comment by sgiehl** [comment]
Thx for the suggestion. The linked PR will change that. Will be included in the next version I will publish later :+1:
