### ISSUE TITLE
Remove 2 generic bot names

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/device-detector#5480]
Hi,

i detected 2 generics bot names, which could be removed.
Or is a bot name always required?

https://github.com/piwik/device-detector/blob/master/regexes/bots.yml#L1189-L1202
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/PiwikDeviceDetector.php#L79-L80

**Comment by sgiehl** [comment]
Current implementation requires a not empty result. so I need to set `name` or `category`
But I could always use `Generic bot` instead of `Bot` aswell.

**Comment by ThaDafinser** [comment]
Okay thats fine, just wanted to know it :+1:
