### ISSUE TITLE
Valid UA being detected as a bot?

### ISSUE THREAD

**Issue by pete001** [piwik/device-detector#5484]
Hi there, we use your library extensively, it rocks! We think we found a UA thats being flagged as a bot, but we believe its legit.

```
Mozilla/5.0 (Linux; Android 5.1; FEVER Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Mobile Safari/537.36
```

From what we can tell, this was a real user, therefore it shouldnt be returning true for `isBot()`.

**Comment by sgiehl** [comment]
Thx for your feedback. That is a false/positive indeed. I'll fix that.
Btw. if you have a list of more undetected or incorrect detected user agents feel free to send them to me (stefan@piwik.org)

**Comment by pete001** [comment]
Awesome!! Yeah for sure, we have millions of user agent strings passing through this every day, these seem a real edge case but i will ensure we log them out and ill send them over when we receive them :-)
