### ISSUE TITLE
Opera 7 was the first browser to use Presto

### ISSUE THREAD

**Issue by NielsLeenheer** [piwik/device-detector#5499]
````Opera/6.04 (Windows 2000; U) [en]````

The token "Presto" is not present here (and it shouldn't be, because Opera 6 doesn't use Presto), but it is 
wrongly detected as the rendering engine.

````
Array
(
    [client] => Array
        (
            [type] => browser
            [name] => Opera
            [short_name] => OP
            [version] => 6.04
            [engine] => Presto
        )
    ...
)
````

**Comment by sgiehl** [comment]
Presto is now assumed for Opera > 7. For Opera between 3.5 and 7 the engine was called Elektra. In versions before 3.5 there wasn't even a name for the engine, so it isn't assumed now anymore.
