### ISSUE TITLE
Add detection of Line on Android

### ISSUE THREAD

**Issue by tflin** [piwik/device-detector#5530]
The Line client app is detected on iOS platform but not on Android. Please include detect of it. Line is the most popular instant messenger app in Asian countries including Japan, Taiwan, Thailand, HongKong...etc.
The UA strings of Line on Android are like:

Mozilla/5.0 (Linux; Android 6.0.1; HTC_B810x Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36 Line/6.5.0/IAB

Mozilla/5.0 (Linux; Android 5.0; ASUS_Z00AD Build/LRX21V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 Line/6.5.1/IAB

Mozilla/5.0 (Linux; Android 6.0.1; MI 3W Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Mobile Safari/537.36 Line/6.5.2/IAB

**Comment by sgiehl** [comment]
That seems already fixed. Checked the mentioned UAs and all show Line as client
