### ISSUE TITLE
LenovoG780 laptop is recognized as smarthpone and desktop and mobile

### ISSUE THREAD

**Issue by DaimonPl** [piwik/device-detector#5545]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36 SailfishBrowser/Rulz ~LenovoG780

It's laptop and is recognized as smartphone + both is_desktop and is_mobile are true

**Comment by sgiehl** [comment]
can you confirm that the user agent really includes the `~LenovoG780` at the end? Otherwise it's not possible to detect the device here at all.

**Comment by DaimonPl** [comment]
yes, that's full UA as found in page views
