### ISSUE TITLE
ZTE brand detected as ZT

### ISSUE THREAD

**Issue by jsmad** [piwik/device-detector#5555]
I noticed that in some cases, a ZTE Blade 580 came up as just "ZT".

For example, the user agent string:

```
Mozilla/5.0 (Linux; Android 5.1; ZTE Blade V580 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.124 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/96.0.0.17.70;]
```

getBrand() returns the string:

```
ZT
```

**Comment by sgiehl** [comment]
`getBrand` returns a short code. use `getBrandName` to get the full name.

**Comment by jsmad** [comment]
Sorry for the false bug report, but the functions and their results are bit misleading.

For example:

getOS() returns name = Facebook
getDevice() returns name = Android

but why does getBrand() return a short name? and has a separate function of getBrandName for the full name? even more confusing, is that getDevice also returns a "short_name" in the return array.
