### ISSUE TITLE
Nexus 5 not detected if using Firefox

### ISSUE THREAD

**Issue by smth** [piwik/device-detector#5565]
I don't know if this can be improved, but when using Firefox on a Nexus 5, brand and model are returned empty.

**Comment by sgiehl** [comment]
would you mind looking up the useragent?

**Comment by smth** [comment]
Mozilla/5.0 (Android 6.0.1; Mobile; rv:50.0) Gecko/50.0 Firefox/50.0

**Comment by sgiehl** [comment]
Hm... As there is no information in the user agent that could point to the model or brand there isn't anything that can be done.
