### ISSUE TITLE
Is Google the correct brand for Nexus phones?

### ISSUE THREAD

**Issue by smth** [piwik/device-detector#5567]
While being flagship products for Google, Nexus 5 is branded LG, and Nexus 6 Huawei.

**Comment by sgiehl** [comment]
It's correct that Nexus and other devices are produced by LG, Huawei, HTC or any other producer. But in this case it's exclusively been sold by Google. If the producer would sell the devices as their own, as well, I would change the brand, but I don't think it makes much sense here as it might be more confusing
