### ISSUE TITLE
isTouchEnabled - array instead of boolean

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/device-detector#5568]
While trying out https://github.com/piwik/device-detector/issues/5375 here http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%3B+Trident%2F7.0%3B+Touch%3B+rv%3A11.0%29+like+Gecko

I recognized that isTouchEnabled returns an array, instead of a boolean
![image](https://cloud.githubusercontent.com/assets/533017/21760300/482b61c6-d64b-11e6-954b-7c8339372c16.png)

**Comment by ThaDafinser** [comment]
Method used `isTouchEnabled()`
![image](https://cloud.githubusercontent.com/assets/533017/21760310/607685da-d64b-11e6-9e23-41b70bb400fa.png)

**Comment by sgiehl** [comment]
Thanks for the note: I'll change that to return boolean instead.
