### ISSUE TITLE
getDevice often empty

### ISSUE THREAD

**Issue by smth** [piwik/device-detector#5571]
Firstly, I'm assuming that `getDevice` is intended to return a `0` or `1`, based on whether the device is a desktop or mobile. Is that correct?

I've been testing with [Useragent-Switcher](http://mybrowseraddon.com/useragent-switcher.html), and found that with some useragents, `getDevice` is empty, despite the word "mobile" being in the useragnet. For example:

```
Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)
```

Is this intentional? Just wondering if `getDevice` should/could be relied upon as an either/or.

**Comment by sgiehl** [comment]
It should return one of the following values:
see https://github.com/piwik/device-detector/blob/master/Parser/Device/DeviceParserAbstract.php#L25-L35
If it returns `null` the type couldn't be detected savly.

If you want to check for mobile or desktop use `isMobile()` or `isDesktop()` instead
