### ISSUE TITLE
If BrowserEngine couldn't be detected, YamlParser falls back to Spyc even though it was configured for Symfony

### ISSUE THREAD

**Issue by saschaglo** [piwik/device-detector#5573]
Hi folks,

following scenario:

Test against this user agent:

Mozilla/5.0 (BlackBerry; U; BlackBerry AAAA; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/X.X.X.X Mobile Safari/534.11+

Browser engine couldn't be detected, so the Browser class instantiates the Engine class the determine the browser engine. The issue here is that cache and yaml parsers are not set, means, you have to change this:

```php
if (empty($engine)) {
    $engineParser = new Engine();
    $engineParser->setUserAgent($this->userAgent);
    $engine = $engineParser->parse();
}
```

to

```php
if (empty($engine)) {
    $engineParser = new Engine();
    $engineParser->setYamlParser($this->yamlParser);
    $engineParser->setCache($this->cache);
    $engineParser->setUserAgent($this->userAgent);
    $engine = $engineParser->parse();
}
```

**Comment by sgiehl** [comment]
fixed in 832e019cce6d921d43d246eb65af86b8c9001a2c
