### ISSUE TITLE
How to find unknown user agents?

### ISSUE THREAD

**Issue by d4rken** [piwik/device-detector#5576]
I'm looking to reduce the `UNKNOWN` count in Piwiks device column.

I'm collecting a huge log file of user agents and would like to filter out those that are unknown to device-detector.

Assume that we've got a text file containing one user agent per line.
How would I best do that? Maybe some bash magic?

**Comment by shaeney** [comment]
well, you could start by creating rexexes that match against each user agent that you have and manually decode them into an appropriate result?

If you can provide an example user agent, that would be a start

**Comment by Findus23** [comment]
If it helps you: The following command is mentioned on http://devicedetector.net/index.php?r=site%2Fabout to get a list of top user agents:
```bash
zcat ~/path/to/access/logs* | awk -F'"' '{print $6}' | sort | uniq -c | sort -rn | head -n20000 > /home/piwik/top-user-agents.txt
```

Then you could write a small php script which loops through them and filter the ones, which are unknown to device-detector.
I might look into it, if I have time.

**Comment by Findus23** [comment]
Simple example script (modified example from README.MD):
```php
<?php
require_once 'vendor/autoload.php';

use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\DeviceParserAbstract;

$userAgentList = file("userAgents.txt", FILE_IGNORE_NEW_LINES);


foreach ($userAgentList as $userAgent) {

    $dd = new DeviceDetector($userAgent);

// OPTIONAL: Set caching method
// By default static cache is used, which works best within one php process (memory array caching)
// To cache across requests use caching in files or memcache
    $dd->setCache(new Doctrine\Common\Cache\PhpFileCache('./tmp/'));

// OPTIONAL: If called, getBot() will only return true if a bot was detected  (speeds up detection a bit)
    $dd->discardBotInformation();

    $dd->parse();

    if (!$dd->isBot()) {
        $clientInfo = $dd->getClient(); // holds information about browser, feed reader, media player, ...
        $osInfo = $dd->getOs();
        $device = $dd->getDevice();
        $brand = $dd->getBrandName();
        $model = $dd->getModel();
        if (!$clientInfo && !$osInfo ) {
            echo $userAgent . "\n";
        }
    }

}
```

My small sample returns only a few bots that weren't detected (e.g. `Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)`), but adding them isn't that important as they will newer show up in Piwik.

**Comment by sgiehl** [comment]
Just added Let's Encrypt ;)
If you guys have more undetected user agent Pull Requests are very welcome.
Or feel free to simply create issues with undetected user agents.

**Comment by Findus23** [comment]
> If you guys have more undetected user agent Pull Requests are very welcome.
I'll look into it. Just one question: How are the yml files sorted? (so where should I add new bots?) Alphabetically by name?

**Comment by sgiehl** [comment]
Guess they aren't ordered anymore. Btw. would be nice if you could add some tests, as well.

**Comment by d4rken** [comment]
@Findus23 Thanks for the modified example. Is there a guide to getting this up and running somehow? I assume through composer? (Really not that into php)

@sgiehl Will make issue tickets for the most common ones, still collecting a bit more. It will be all Android devices. Currently at 23825 unique ones which I still have to jam through the detector to find the unknown ones.

**Comment by Findus23** [comment]
@d4rken copy it into an empty directory, run `composer require piwik/device-detector` and `composer require doctrine/cache`
Then run the script with `php script.php`. (Assuming the input file is called `userAgents.txt`)

**Comment by d4rken** [comment]
So far so good, I can run the detection. How to I get the unit tests running?

**Comment by sgiehl** [comment]
simply run `phpunit` in base directory of device detector.
Or if you haven't it installed global run `./vendor/bin/phpunit`

**Comment by d4rken** [comment]
Thanks. Ah that worked. I tried to install it globaly but then running it would just say `No tests executed!`

I've got a file with 11027 unique unknown user agents, currently filtering again. Removing Android versions to only get unique devices. Then sort my most common ones.

I'll do a PR for a few to get a hang of php testing. How to supply the rest? Just put them all in a ticket?

**Comment by sgiehl** [comment]
Sure. Simply paste them in a ticket. I'll try to go through them and add detections when I have time to
