### ISSUE TITLE
Grapeshot crawler not tracked

### ISSUE THREAD

**Issue by palpalani** [piwik/device-detector#5577]
Is Grapeshot crawler caught?
https://www.grapeshot.com/crawler/

**Comment by ThaDafinser** [comment]
@palpalani u can try it out
http://devicedetector.net/?ua=Mozilla%2F5.0+%28compatible%3B+GrapeshotCrawler%2F2.0%3B+%2Bhttps%3A%2F%2Fwww.grapeshot.com%2Fcrawler%2F%29
http://devicedetector.net/?ua=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+8_3+like+Mac+OS+X%29+AppleWebKit%2F600.1.4+%28KHTML%2C+like+Gecko%29+Version%2F8.0+Mobile%2F12F70+Safari%2F600.1.+4+%28compatible%3B+GrapeshotCrawler%2F2.0%3B+%2Bhttps%3A%2F%2Fwww.grapeshot.com%2Fcrawler%2F%29

or
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28compatible%3B+GrapeshotCrawler%2F2.0%3B+%2Bhttps%3A%2F%2Fwww.grapeshot.com%2Fcrawler%2F%29

**Comment by sgiehl** [comment]
It is detected as generic bot already, but I'll improve that.
