### ISSUE TITLE
User Agents with "Mobile" in default to Desktop

### ISSUE THREAD

**Issue by shaeney** [piwik/device-detector#5578]
HI guys, first off, what a fantastic bit of code!!!! really helpful.

After debugging, I can see the default to desktop, which is understandable.

However, I can see User AGents, such as below, are not detected as smartphone, despite the user agent containing "Mobile"?

"Mozilla/5.0 (Linux; Android 5.1; Z820 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36"

I could create my own yml mappings for this, but I wouldnt want to get out of sync with the repo?

**Comment by sgiehl** [comment]
Have you tried using the `isMobile()` method. That should return true in that case even if no smartphone was detected.

**Comment by shaeney** [comment]
I've searched the code I have and cant find the isMobile() method?

**Comment by sgiehl** [comment]
See https://github.com/piwik/device-detector/blob/master/DeviceDetector.php#L351

**Comment by shaeney** [comment]
Ah, so I am looking at a C# equivalent, but the issue will remain - thet user agent is resolved to device type of "desktop"

**Comment by sgiehl** [comment]
Maybe the C# version is not uptodate. Current PHP lib already detects it as smartphone. But the model / brand is missing for that useragent. I'll try to add that

**Comment by sgiehl** [comment]
I've added the detection for your mentioned user agent. If you have more undetected ones, feel free to create issues for them.
