### ISSUE TITLE
Prestigio Regex

### ISSUE THREAD

**Issue by shaeney** [piwik/device-detector#5581]
The RegEx for the Prestigio SmartPhone is

((?:PAP|PSP)[0-9]+[a-z0-9_]+(?: DUO)?)[);/ ]

A typical User Agent is:

Mozilla/5.0 (Linux; Android 4.4.2; PSP5453DUO Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36

In the Microsoft .Net Regular Expression matcher, they do not match, due to the "[);/ ]" at the end or the RegEx?

Using the online tool @ https://regex101.com/ this doesnt match either (after escaping the /)?

**Comment by sgiehl** [comment]
Regexes in device detector are matched case insensitive. On https://regex101.com/ it works case insensitive (after escaping the /).

**Comment by sgiehl** [comment]
Btw. your mentioned user agent is correctly detected on our demo @ http://devicedetector.net

**Comment by shaeney** [comment]
Cheers - i've come to the same colclusion that it's the case.

The Wiko Slide is another one, where the actual case is different. 

Loving your work, by the way!

**Comment by shaeney** [comment]
I've now put in case insensitive RegEx.

The Test website is matching the following to smartphone:
Mozilla/5.0 (Linux; Android 7.0; F8331 Build/39.2.A.0.417) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

But I cant find a macthing regex in the Mobiles yml????? How does the site match this to a smartphone?
