### ISSUE TITLE
Getting regex output

### ISSUE THREAD

**Issue by da-pingwing** [piwik/device-detector#5590]
Hi,

Is it possible to get:

(?:Honor_|HW-)?H60-L(?:01|02|03|04|11|12)(?:_TD)?[);/ ] The output of this regex to a string like:

Input: H60-L11.... (the user agent..)
- Model: Honor 6
- ModelPreParse: H60-L11

So basically what the regex matches also as a variable?

Greetings,

**Comment by sgiehl** [comment]
Most regexes matches more than only one useragent. So no, that's not possible at the moment, and I don't think thats easy to make. What would you need that for?

**Comment by cloviswarlop229** [comment]
Already made it do what i wanted, i might have explained badly.

I will comment with my code later and also include the devices i added (the new huawei's are missing)
