### ISSUE TITLE
Add Electron support

### ISSUE THREAD

**Issue by bontibon** [piwik/device-detector#5597]
Adding this will help detect a visit by a Chrome browser vs. an Electron app.

Example user agent:

````
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) SampleElectronApp/0.1.0 Chrome/52.0.2743.82 Electron/1.3.13 Safari/537.36
````

Browser: Electron
Browser family: Chrome

**Comment by sgiehl** [comment]
Not sure if we should add `Electron`  as new browser. Actually it's a framework for desktop apps.
In the useragent you provided would `SampleElectronApp` be the client name I guess.
