### ISSUE TITLE
Windows Phone device detected as "Apple Iphone"

### ISSUE THREAD

**Issue by nodeffect** [piwik/device-detector#5598]
Found a bug where it detects Windows phone as "iPhone". Details as below:

User agent:
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1141) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

Smartphone device detected as "Apple iPhone".

Please see this link below for more details:
http://devicedetector.net/?ua=Mozilla%2F5.0+%28Mobile%3B+Windows+Phone+8.1%3B+Android+4.0%3B+ARM%3B+Trident%2F7.0%3B+Touch%3B+rv%3A11.0%3B+IEMobile%2F11.0%3B+Microsoft%3B+RM-1141%29+like+iPhone+OS+7_0_3+Mac+OS+X+AppleWebKit%2F537+%28KHTML%2C+like+Gecko%29+Mobile+Safari%2F537

**Comment by sgiehl** [comment]
I'll add a detection for this specific device RM-1141 (Lumia 540). But that won't prevent any other incorrect detections for Windows phone devices. The useragents they use are completely non-sense. It includes fragments of three operating systems - Windows, Android and iOS.

**Comment by nodeffect** [comment]
sorry, I dont know why it returns this weird user agent... my bad for not looking clearly.

**Comment by sanchezzzhak** [comment]
parse file yml error
http://joxi.net/L21GM7yu6Gw5Kr
error
PHPUnit_Framework_Error_Warning : Illegal string offset 'user_agent'
 C:\home\server\nginx\www\detector\device-detector\Tests\DeviceDetectorTest.php:121

**Comment by sanchezzzhak** [comment]
php 7.11RC
