### ISSUE TITLE
Media player detection are ignored in browsers

### ISSUE THREAD

**Issue by bigretromike** [piwik/device-detector#5615]
Hello,

Thank you for great plugin.
Im using default piwik installation. 
At Diagnostic menu, Device is detected corectly - as Media Player, which is correct as regex is inside media player file (its default one, not edited by me). But at any given raport on dashboard all of those MediaPlayers are shown as UNKNOWN, which looks like a error. Do I have to change setting of PIWIK that he use device detector plugin correctly or it just intended way to detect it and report ? I see multiply UNKNOW rows in reports that looks like it agregate them by mediaplayer version, but show them as unknow.

Edit: I dont see any mediaplayer that was detected correctly nowhere (client/software) I would assume that is should show up in software...

**Comment by sgiehl** [comment]
Device Detector is integrated in Piwik. If device is detected in diagnostic menu it should also be detected the same within Piwik. There is only one exception. Piwik currently discards client information if the client is not a browser.
Would you mind sharing the useragent?

**Comment by bigretromike** [comment]
`Kodi/17.1 (X11; Linux aarch64) LibreELEC/8.0 App_Bitness/64 Version/17.1-Git:fc1619b`
`Kodi/17.0-ALPHA2 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.0-ALPHA2-Git:20160619-d11a5d7`
for example

**Comment by bigretromike** [comment]
How could I bypass that `one exception`

**Comment by sgiehl** [comment]
There is currently no easy possibility to bypass that. We need to adjust a bit more in Piwik to make it possible to store all clients

**Comment by sgiehl** [comment]
This will be fixed as soon as we have some time to work on https://github.com/piwik/piwik/issues/5413

**Comment by bigretromike** [comment]
if i move code from `mediaplayers.yml` and move i to `browsers.yml` and add bit code to `Browser.php` will I have to anything else for piwik to think that my media player is browser ?

**Comment by sgiehl** [comment]
you may need a short code for that in Browser.php. Piwik only uses those short codes internally and fetches the full name only for displaying it. 
Keep in mind: Changing that might cause problems if we later add a shortcode related to another browser. Also this will make is difficult for you to update Piwik as automatic update will overwrite your changes

**Comment by bigretromike** [comment]
I understand the cons of this and understand that this is only 'workaround'. Good because I was afraid I will need purge my database and re-import it. Thanks for help

**Comment by sgiehl** [comment]
Changing that now won't affect any already imported/tracker visits. Also it might results in problem if we solve the client detection in Piwik and migrate existing data automatically

**Comment by bigretromike** [comment]
As I understand the danger of this, I need to have it from `now` 👍 
Hope the #5413 get there eventually - until then i need solution 👍 

Thanks again for great plugin
