### ISSUE TITLE
Patch version isn't parsed properly.

### ISSUE THREAD

**Issue by NavyCoat** [piwik/device-detector#5618]
Hello,

MobileDetector didn't consider more than 2 elements of version.

By parsing "Android/3.11.2 (175;Phone;6.0.1;Xiaomi MI 5s Plus)"
I expect to get:
`$mobile->getOs('version') // returns '3.11' - expceted '3.11.2'`

or in "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
`$mobile->getClient('version') // returns '58.0' - expceted '58.0.3029.110'`

It's should be fixed I think. Thanks :)

**Comment by sgiehl** [comment]
You may need to call this in front:
`DeviceParserAbstract::setVersionTruncation(DeviceParserAbstract::VERSION_TRUNCATION_NONE);`
Otherwise Versions will always be truncated to `X.Y`.
