### ISSUE TITLE
Split Firefox into mobile and desktop (similar to Chrome)

### ISSUE THREAD

**Issue by Findus23** [piwik/device-detector#5621]
from https://forum.piwik.org/t/piwik-firefox-user-agent/24463/

All Firefox Browsers are just called "Firefox" (https://github.com/piwik/device-detector/blob/master/regexes/client/browsers.yml#L177) and as a result are grouped as one browser in Piwik.

On the other hand Chrome is split up in "Chrome" and "Chrome Mobile" (https://github.com/piwik/device-detector/blob/master/regexes/client/browsers.yml#L462).

We should decide which one is correct and change the other one.

**Comment by sgiehl** [comment]
Guess we could add a new detection for Firefox Mobile, which also checks for the `Tablet` and `Mobile` fragments.

**Comment by sgiehl** [comment]
@Findus23 are you able to propose a PR for that? Not sure if I will find some time before the next release...
