### ISSUE TITLE
parse file  table1.yml error PHP 7.11RC

### ISSUE THREAD

**Issue by sanchezzzhak** [piwik/device-detector#5622]
screen problem
http://joxi.net/L21GM7yu6Gw5Kr
error
PHPUnit_Framework_Error_Warning : Illegal string offset 'user_agent'
C:\home\server\nginx\www\detector\device-detector\Tests\DeviceDetectorTest.php:121

**Comment by sgiehl** [comment]
Will check if that needs to be escaped. I've also enabled tests for PHP 7.1 now...

**Comment by sanchezzzhak** [comment]
I think I made a hasty conclusions.
all reset my code & branch 
after run test, test performed success

pls close issue, sorry
