### ISSUE TITLE
 LYF detect two names model, what name model should I use?

### ISSUE THREAD

**Issue by sanchezzzhak** [piwik/device-detector#5623]
```
Mozilla/5.0 (Linux; Android 5.1.1; LS-4503 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36 
```
about the device - LYF LS-4503. Is it correct to name model as LS-4503 or I have to use alternative model name - LYF Flame 1?

**Comment by sgiehl** [comment]
I usually try to use the alternative model names. Makes it easier to identify the devices and in some cases on there a multiple devices with the same alternative name (like [here](https://github.com/piwik/device-detector/blob/master/regexes/device/mobiles.yml#L3758-L3760))
