### ISSUE TITLE
Brave Browser showing as Chrome on iOS. 

### ISSUE THREAD

**Issue by AhsanE** [piwik/device-detector#5632]

**Comment by sgiehl** [comment]
Can you post the useragent?

**Comment by AhsanE** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36                    


Brave spoofs user agent :/

**Comment by sgiehl** [comment]
So there is no way to detect it :disappointed:

**Comment by AhsanE** [comment]
I found a way to detect, its very complicated. I dont want them to know how it works, so I will obfuscate it. If you want I can submit.

**Comment by sgiehl** [comment]
I can't see any possibility to detect that based on the useragent. But if you have one, feel free to create a Pull Request. I'm happy to merge if it makes sense and won't produce incorrect detections for other user agents.

**Comment by AhsanE** [comment]
Its based on external scripts. There is a little chance of false positives, its based on probability.

**Comment by sgiehl** [comment]
I wouldn't like to include external scripts for a browser detection. That might slow down each detection a lot

**Comment by AhsanE** [comment]
Well I made the scripts. Takes, 50ms-1500ms, with no overhead, just time.

**Comment by sgiehl** [comment]
I appreciate your offer, but I won't include any obfuscated scripts. This code is open source, and all detections should be public "visible", so everyone is able to change whatever he wants to.

**Comment by AhsanE** [comment]
As you wish. The reason to obfuscate is so that Brave wont understand logic.

**Comment by ToX82** [comment]
I'm not sure if this could be integrated in a php project, but brave is reliably detectable using this line in javascript:

`(navigator.brave && await navigator.brave.isBrave() || false)`
