### ISSUE TITLE
Facebook messenger detection

### ISSUE THREAD

**Issue by etienne-martin** [piwik/device-detector#5646]
Facebook messenger is detected as the facebook mobile app. However, the version number displayed is that of facebook messenger.

```javascript
"client": {
    "type": "mobile app",
    "name": "Facebook",
    "version": 132 // <-- Facebook messenger version number
}
```

Here are two user agents from messenger, one on iOS and the other on Android. Both contain the string `messenger`:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 [FBAN/MessengerForiOS;FBAV/132.0.0.41.90;FBBV/69171754;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/10.3.3;FBSS/2;FBCR/Koodo;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (Linux; Android 7.1.2; Nexus 5X Build/N2G47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/114.0.0.21.71;]
```

Here's a long list of user agents gathered from facebook messenger: https://gist.github.com/etienne-martin/bea6b38c6999c720d91bd77010fae4f4

I would like to add support for these user agents but I suck at regex.

Can someone help me with that?

**Comment by sanchezzzhak** [comment]
```
FBAN: FaceBook Application Name
FBAV: FaceBook Application Version
FBBV: FaceBook Build Version
FBDV: FaceBook Device Version
FBMD: FaceBook Major Device
FBSN: FaceBook System Name
FBSV: FaceBook System Version
FBSS: FaceBook System Something :)
FBCR: FaceBook CarrieR
FBID: FaceBook Identity of Device
FBLC: FaceBook Language Code
```

**Comment by etienne-martin** [comment]
Here's the regex I came up with:

```yml
# Facebook Messenger
- regex: '(?:MessengerForiOS|MESSENGER).(?:FBAV)(?:[ /]([\d\.]+))?'
  name: 'Facebook Messenger'
  version: '$1'
```

I tested it with these two user agents and it seems to work fine.

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 [FBAN/MessengerForiOS;FBAV/132.0.0.41.90;FBBV/69171754;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/10.3.3;FBSS/2;FBCR/Koodo;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (Linux; Android 7.1.2; Nexus 5X Build/N2G47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/114.0.0.21.71;]
```

Can someone tell me if I'm missing something before I create a pull request?

**Comment by jobportals** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
501.x Series
--
✅ 501.0.0.61.70 (Stable)
✅ 501.0.0.49.70 (Beta)
✅ 501.0.0.41.70 (Beta)
✅ 501.0.0.33.70 (Beta)
500.x Series
✅ 500.0.0.57.50 (Stable)
✅ 500.0.0.41.50 (Beta)
✅ 500.0.0.35.50 (Beta)
✅ 500.0.0.19.50 (Beta)
499.x Series
✅ 499.0.0.31.60 (Stable)
✅ 499.0.0.30.60 (Beta)
✅ 499.0.0.27.60 (Beta)
✅ 499.1.0.22.60 (Beta)
498.x & 497.x Series
✅ 498.1.0.64.74 (Stable)
✅ 497.0.0.47.36 (Stable)


</body>
</html>
