### ISSUE TITLE
Mozilla/5.0 SeznamEmailProxy/2.0.174

### ISSUE THREAD

**Issue by razseo** [piwik/device-detector#5668]
Hello, seams, that it's like google image proxy.
Please check it.
UA:  Mozilla/5.0 SeznamEmailProxy/2.0.174
IP:  77.75.78.150

**Comment by Findus23** [comment]
I don't think this is the google image proxy, but rather a bot proxying images in email for the Webmailer of the Czech E-Mail Provider Seznam.
https://napoveda.seznam.cz/cz/email/imap-pop3-smtp/

**Comment by razseo** [comment]
As i write - LIKE google images proxy at GMAIL.

**Comment by Findus23** [comment]
Ah, sorry, I missed that.

**Comment by razseo** [comment]
- regex: 'Seznam Email Proxy'
  name: 'SeznamEmailProxy'
  category: 'Crawler'
  url: ''
  producer:
    name: 'Seznam.cz, a.s.'
    url: 'http://www.seznam.cz/'

**Comment by razseo** [comment]
Merged.
