### ISSUE TITLE
LOGICOM Tablette tactile M BOT TAB

### ISSUE THREAD

**Issue by mkdev-jaugusto** [piwik/device-detector#5674]
Hi,

Some LOGICOM tablets, are being detected as BOT's

Thanks,

**Comment by sgiehl** [comment]
Can you provide an example user agent of a device detected as bot?

**Comment by mkdev-jaugusto** [comment]
Mozilla/5.0 (Linux; Android 6.0.1; M BOT TAB 101 Build/MOB30R) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Safari/537.36

**Comment by sgiehl** [comment]
That's because of the ` BOT ` within the user agent. Why on earth is someone calling their device BOT 🙄 
Will check later if there is an easy way to fix that....
