### ISSUE TITLE
Google Pixel devices with Android 8 always detected as Opera browser.

### ISSUE THREAD

**Issue by interfrnc** [piwik/device-detector#5675]
Hey,

The new Anroid 8 builds for Google Pixel contains the `OPR `string and it automatically sets the browser to Opera with every browser.

Test user agent:

`Mozilla/5.0 (Linux; Android 8.0.0; Pixel Build/OPR3.170623.008) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36` 

More info : https://developers.google.com/android/images

Thank you for any help you can provide.

**Comment by sgiehl** [comment]
Thanks for the report. I'll try to fix that.

**Comment by interfrnc** [comment]
Thank you for the quick fix.
When are you planning the next release ?

**Comment by sgiehl** [comment]
will do one now ;)

**Comment by interfrnc** [comment]
Thank you ! :)
