### ISSUE TITLE
Bot detection improvement

### ISSUE THREAD

**Issue by i-gabdushev** [piwik/device-detector#5681]
Hi there
Found that these ua is not recognized as bots

- Mozilla/5.0 (compatible; SMTBot/1.0; +http://www.similartech.com/smtbot)
- Mozilla/5.0 (compatible; Discordbot/1.0; +https://discordapp.com)
- Mozilla/5.0 (compatible; Shareaholicbot/2.0; +http://www.shareaholic.com/bot)
- HybridBot (hybrid.ru/about. If our bot caused problems please contact us. Contact email: m.lyashkov@targetix.net)
- GG PeekBot 2.0 ( http://gg.pl/ http://info.gadu-gadu.pl/praca )
- Mozilla/5.0 (compatible; FemtosearchBot/1.0; http://femtosearch.com)
- woobot/2.0
- Mozilla/5.0 (compatible; DnyzBot/1.0)

**Comment by sgiehl** [comment]
There was a bug in the bot detection. Those should be detected as generic bots again soon...
