### ISSUE TITLE
iPad detection improvments

### ISSUE THREAD

**Issue by dhantke** [piwik/device-detector#5682]
Hi,

it seems that the latest iPad generations are not supported. iPad device detection ends with model iPad6,7 / iPad6,8
[device-detector/regexes/device/mobiles.yml](https://github.com/piwik/device-detector/blob/master/regexes/device/mobiles.yml)
```
    - regex: '(?:Apple-)?iPad6[C,][78]'
      model: 'iPad Pro 12.9'
      device: 'tablet'
```
A full list can be found here https://everyi.com/by-identifier/ipod-iphone-ipad-specs-by-model-identifier.html.

Would be great if the device list can be extended.

**Comment by sgiehl** [comment]
Thanks for the hint. Will add the missing devices...
