### ISSUE TITLE
BBK doesn't seem to have any devices

### ISSUE THREAD

**Issue by Findus23** [piwik/device-detector#5687]
https://github.com/piwik/device-detector/blob/37eabcb46025ad7bec6b939dd344fdf1909f19d5/Parser/Device/DeviceParserAbstract.php#L83

Am I missing something, or are there no detected devices or tests for the device "BBK (![bbk](https://user-images.githubusercontent.com/6266037/33234185-80a6be00-d222-11e7-94cf-08e843687bee.png))?

Is it possible that it is still left over from an old version of DeviceDetector?

**Comment by sgiehl** [comment]
Hm. not sure why it is there. But as it has no detected devices, guess I'll add some detections for it :stuck_out_tongue:

**Comment by sgiehl** [comment]
Ok. Seems BBK itself doesn't have any devices, but some other brands are owned by them, like Vivo, Oppo and OnePlus. Not sure if in old versions were any detections for BBK. If so we should leave it here.

**Comment by Findus23** [comment]
I have replaced it now with a higher resolution icon:
![bbk svg](https://user-images.githubusercontent.com/6266037/33234391-4a23d698-d226-11e7-8e43-9f7b63347446.png)
