### ISSUE TITLE
new bots (MetaInspector) and java

### ISSUE THREAD

**Issue by 22h** [piwik/device-detector#5694]
To begin with, I would like to know if there is a reason why Java is not declared as a bot.

For example:
- `Java/1.8.0_25`
- `Java/1.8.0_77`

I also have a UserAgent here, which in my opinion should also be detected as a bot.
`MetaInspector/5.4.0 (+https://github.com/jaimeiniesta/metainspector)`

**Comment by sgiehl** [comment]
> To begin with, I would like to know if there is a reason why Java is not declared as a bot.

Java is a programming language, and thus more like a framework or library in this context. It does not need to be used for bots only.

**Comment by 22h** [comment]
Right, I didn't see the library option. That was my mistake.
What about MetaInspector? Would you include these?

**Comment by sgiehl** [comment]
done :)
